# Generated by Django 4.2.4 on 2023-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_remove_question_lesson_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='Default Question Text, Please add a New One'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Default Title, Please add a New One', max_length=100),
        ),
    ]
