# Generated by Django 4.2.4 on 2023-08-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_choice_question_title_alter_choice_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_title',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinecourse.question'),
        ),
    ]
