# Generated by Django 4.2.4 on 2023-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_remove_choice_question_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.IntegerField(default=0),
        ),
    ]
