# Generated by Django 4.2.4 on 2023-08-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0008_submission_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
    ]
