# Generated by Django 4.2.4 on 2023-08-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0009_rename_chocies_submission_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='course',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='choice_text', max_length=200),
        ),
    ]
